simya_web5/Controllers/AdminNewsController.cs
using simya_web5.Models; 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace simya_web5.Controllers
{
    public class AdminNewsController:Controller
    {
        SimyaDBContext db = new SimyaDBContext();
        // GET: /News/Index
        public ActionResult Index()
        {
            List<news> news_list = new List<news>();
            news_list = db.news.ToList();
            List<lang> langs_list = new List<lang>();
            langs_list = db.langs.ToList();
            ViewBag.Langs = langs_list;
            ViewBag.News = news_list;
            return View();
        }
        // GET: /News/Add
        public ActionResult Add(int? id)
        {
            List<lang> langs_list = new List<lang>();
            langs_list = db.langs.ToList();
            ViewBag.Langs = langs_list;
            return View();
        }

        [HttpPost]
        public ActionResult Add()
        {
            var x_news = new news();   
            ViewBag.BackLinki = Url.Action("Index", "Admin");

            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    x_news.langId = 1;
                    //magaza.YetkiliAdi = YetkiliAdi;
                    //magaza.YetkiliSoyadi = YetkiliSoyadi;
                    //magaza.EpostaAdres = EpostaAdres;
                    //magaza.TelefonNo = TelefonNo;
                    //magaza.Sehir_ID = SehirID;
                    //magaza.Ilce_ID = IlceID;
                    //magaza.Mahalle = Mahalle;
                    //magaza.Cadde = Cadde;
                    //magaza.Sokak = Sokak;
                    //magaza.KapiNo = KapiNo;
                    //magaza.PostaKodu = PostaKodu;
                    //magaza.Enlem = Convert.ToDouble(Latitude);
                    //magaza.Boylam = Convert.ToDouble(Longitude);
                    ////magaza.Enlem = Convert.ToDouble(enlem[0]+","+enlem[1]);
                    ////magaza.Boylam = Convert.ToDouble(boylam[0] + "," + boylam[1]); 
                    //magaza.MetrekareBrut = MetrekareBrut;
                    //magaza.MagazaPlani = Session["MagazaPlanPath"].ToString();
                    //magaza.PanoSemasi = Session["PanoSemasiPath"].ToString();
                    //magaza.AlinanIzinler = Session["IzinlerPath"].ToString();
                    //magaza.OlusturulmaTarih = DateTime.Now;
                    //magaza.Durum = true;
                    //db.Magaza.Add(magaza); 
                    db.SaveChanges();
                    return Json(true); 
                }
                catch
                {
                    transaction.Rollback();
                    return Json(false);
                }
            }
            return Json(false);
        }
    }
}

simya_web5/Views/AdminNews/Add.cshtml
@model simya_web5.Models.news
@{
    ViewBag.Title = "Admin Paneli";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div id="content">
    <div id="content-header">
        <h1>Haber Ekle</h1>
        <div class="btn-group">
            <a href="javascript:history.back();" class="btn btn-small btn-primary"><i class="icon-arrow-left icon-white"></i> Geri</a>
            <a href="javascript:void(0);" class="btn btn-small btn-primary help-button"><i class="icon-question-sign icon-white"></i> Yardım</a>
        </div>
    </div>

    <div id="breadcrumb">
        <a href="javascript:void(0);"><i class="icon-home"></i> Haberler</a>
        <a href="javascript:void(0);" class="current">Ekle</a>
    </div>

    <div class="tabs-help-wrapper"></div>
    <script type="text/javascript">
        $(function () {
            help('.tabs-help-wrapper', ['language', 'date', 'title', 'description', 'keywordSeo', 'descriptionSeo']); //  help('class ismi',['alan1','alan2']);
        });
    </script>

    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="widget-box">
                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-align-justify"></i>
                        </span>
                        <h5>Haber Ekleme Formu</h5>
                    </div>
                    <div class="widget-content nopadding">
                        <div class="control-group">
                            <label class="control-label">Dil</label>
                            <div class="controls">
                                <select name="lang" id="lang" class="form-control input-sm">
                                    @foreach (simya_web5.Models.lang item in ViewBag.Langs)
                                    {
                                        <option value="@item.langId">@item.title</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Tarih</label>
                            <div class="controls">
                                <input type="text" name="datepicker" id="datepicker" class="datepicker" data-date="" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Başlık</label>
                            <div class="controls">
                                <input type="text" name="title" id="title" class="form-control input-sm validate[required]" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Detay</label>
                            <div class="controls">
                                <div class="admin-editor">
                                    <textarea id="description" name="description" class="ck_editor"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label text-right text-danger">&nbsp;</label>
                            <div class="controls text-danger font-italic">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Title (Seo)</label>
                            <div class="controls">
                                <input type="text" name="seoTitle" id="seoTitle" class="form-control input-sm" />
                                <em class="help-block">sfsfsdfdsfdsfds</em>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Keywords (Seo)</label>
                            <div class="controls">
                                <input type="text" name="seoKeywords" id="seoKeywords" class="form-control input-sm" />
                                <em class="help-block">fddsfdsfdsfdsf</em>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Description (Seo)</label>
                            <div class="controls">
                                <input type="text" name="seoDescription" id="seoDescription" value="<?=stripslashes($news->keywords)?>" class="form-control input-sm" />
                                <em class="help-block">dsfdsfdsfdsfdsfdsfdsfsdfdsfsdf</em>
                            </div>
                        </div>
                        <div class="form-actions">
                            <input type="submit" name="btn_ok" id="btn_ok" class="btn btn-primary" value="Kaydet" />
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        $(document).ready(function () {
            $('.datepicker').datepicker();
            $('#myForm').validationEngine();
            $("#btn-ok").click(function () {
                                $.ajax({
                                    url: "@Url.Action("Add", "AdminNews")",
                                    method: "post",
                                    data: {
                                        MagazaAdi: $("#MagazaAdi").val(),
                                        YetkiliAdi: $("#YetkiliAdi").val(),
                                        YetkiliSoyadi: $("#YetkiliSoyadi").val(),
                                        EpostaAdres: $("#EpostaAdres").val(),
                                        TelefonNo: $("#TelefonNo").val(),
                                        SehirID: $("#TabMenuIller").val(),
                                        IlceID: $("#TabMenuIlceler").val(),
                                        Mahalle: $("#Mahalle").val(),
                                        Cadde: $("#Cadde").val(),
                                        Sokak: $("#Sokak").val(),
                                        KapiNo: $("#KapiNo").val(),
                                        PostaKodu: $("#PostaKodu").val(),
                                        Latitude: lat[0] + "," + lat[1],
                                        Longitude: lng[0] + "," + lng[1],
                                        MetrekareBrut: $("#MetrekareBrut").val(),
                                        ProjeID: projeID
                                    },
                                    success: function (veri) {
                                        if (!veri) {
                                            sweetAlert("İşlem Başarısız!", "Kayıt yapılamadı.", "error");
                                            //alert("İşlem Başarısız");
                                        } else {
                                            swal("İşlem Başarılı!", "Kayıt yapıldı.", "success");
                                            var url = "/Proje/ProjeDuzenle/" + projeID;
                                            setTimeout(function () { window.location.href = url; }, 3000);
                                        }
                                    }
                                });
                    });
        });
//]]>
    </script>
</div>

simya_web5/Views/AdminNews/Index.cshtml
@model simya_web5.Models.news
@{
    ViewBag.Title = "Admin Paneli";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div id="content">
    <div id="content-header">
        <h1>Haberler</h1>
        <div class="btn-group">
            <a href="<?=site_url('admin/news/add')?>" class="btn btn-small btn-primary"><i class="icon-plus-circle icon-white"></i> Haber Ekle</a>
        </div>
    </div>

    <div id="breadcrumb">
        <a href="javascript:void(0);"><i class="icon-home"></i> Haberler</a>
        <a href="javascript:void(0);" class="current">Listele</a>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">


                <div class="row">
                    <form action="<?=site_url('admin/news/index')?>" method="post">
                        <div class="pull-left margin-right-10">
                            <select name="lang" id="lang" class="form-control">
                                <option selected="selected" value="0">Dil seçiniz...</option>
                                @foreach (simya_web5.Models.lang item in ViewBag.Langs)
                                {
                                    <option value="@item.langId">@item.title</option>
                                }
                            </select>
                        </div>
                        <div class="pull-left margin-right-10">
                            <input type="text" name="keyword" id="keyword" placeholder="Ara..." class="form-control" value="<?=(getSession('textSearch', 'grpkey_filterNews')) ?  getSession('textSearch', 'grpkey_filterNews') : ''?>">
                        </div>
                        <div class="pull-left margin-right-10">
                            <input type="hidden" name="process" value="filter" />
                            @*<?php if (count(getSession('grpkey_filterNews')) > 1) : ?>*@
                            <a href="<?=site_url('admin/news/index/resetFilters')?>" class="btn btn-sm btn-warning">Temizle</a>
                            @*<?php endif; ?>*@
                            <input type="submit" class="btn btn-sm btn-primary" value="Bul" />
                        </div>
                    </form>
                    <div class="clear"></div>
                </div>


                <div class="widget-box">

                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-align-justify"></i>
                        </span>
                        <h5>Haber Listesi</h5>
                    </div>

                    <div class="widget-content nopadding">
                        <form action="<?=site_url('admin/news/bulkDelete')?>" method="post" id="frm-list">
                            <table class="table table-bordered table-striped table-hover data-table inline-edit-list" id="news-list">
                                <thead>
                                    <tr>
                                        <th width="100"><input type="submit" class="btn btn-dark-red btn-xs" value="Seçilileri Sil" id="btn_bulkDelete" name="btn_bulkDelete" onclick="javascipt:return confirm('Seçili kayıtları silmek istediğinize emin misiniz?');" disabled="disabled" /></th>
                                        <th width="100">Resim</th>
                                        <th>Başlık</th>
                                        <th width="150">Tarih</th>
                                        <th width="125">Dosya Sayısı</th>
                                        <th width="200">İşlemler</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (ViewBag.News.Count != 0)
                                    {
                                        foreach (simya_web5.Models.news item in ViewBag.News)
                                        {
                                            <tr data-id="<?=$value->newsId?>">
                                                <td><input type="checkbox" name="newsId_<?=$value->newsId?>" id="newsId_<?=$value->newsId?>" value="<?=$value->newsId?>" /></td>
                                                <td><img src="<?=getImage(PATH_MEDIA_IMAGE . $value->fileName, 100, 75)?>" /></td>
                                                <td data-field="title" data-langId="<?=$value->langId?>" data-edit="1">@item.title</td>
                                                <td>@item.date.ToString("yyyy-MM-dd")</td>
                                                <td>0</td>
                                                <td style="text-align:center;">
                                                    <a href="<?=site_url('admin/news/active/' . $value->newsId)?>" class="btn btn-small btn-info tip-bottom" title="Yayın Durumu">
                                                        @if (item.active == 1)
                                                        {
                                                            <i class="icon-eye-slash icon-white"></i>
                                                        }
                                                        else
                                                        {
                                                            <i class="icon-eye icon-white"></i>
                                                        }
                                                    </a>
                                                    <a href="<?=site_url('admin/news/addMedia/'.$value->newsId)?>" class="btn btn-small btn-info tip-bottom" title="Medya Ekle"><i class="icon-picture-o icon-white"></i></a>
                                                    <a href="<?=site_url('admin/news/edit/'.$value->newsId)?>" class="btn btn-small btn-info tip-bottom" title="Düzenle"><i class="icon-pencil icon-white"></i></a>
                                                    <a href="<?=site_url('admin/news/delete/'.$value->newsId)?>" class="btn btn-small btn-info tip-bottom" title="Sil" onclick="javascipt:return confirm('Kaydı silmek istediğinize emin misiniz?');"><i class="icon-remove icon-white"></i></a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="5" class="no_record">Henüz eklenmiş bir kayıt bulunmamaktadır.</td>
                                        </tr>
                                    }
                                    </tbody>
                                </table>
                            </form>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>
    @section jsScripts{
        <script type="text/javascript">

            $(document).ready(function () {
                $('input[type=checkbox]').iCheck({
                    checkboxClass: 'icheckbox_flat-blue'
                });

                $('#frm-list input[type=checkbox]').on('ifChanged', function (event) {
                    var count = $('#frm-list input[type=checkbox]:checked').length;
                    if (count > 0) $('#btn_bulkDelete').removeAttr('disabled'); else { $('#btn_bulkDelete').attr({ 'disabled': 'disabled' }); }
                });

                $('body').data('editModule', 'news');
            });
        </script>
    }