simya_web5/Models/poll.cs
namespace simya_web5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("poll")]
    public partial class poll
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long pollId { get; set; }

        public long sort { get; set; }

        public int status { get; set; }

        public int result { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime createDate { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime updateDate { get; set; }

        public int remove { get; set; }
    }
}

simya_web5/Controllers/PollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace simya_web5.Controllers
{
    public class PollController:Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Details()
        {
            return View();
        }
    }
}

simya_web5/Views/Poll/Details.cshtml
@{
    ViewBag.Title = "Deneme - egegen Internet Solutions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link type="text/css" rel="stylesheet" href="~/Content/assets/css/poll/poll.css" />

<div class="section section-content">

    <div class="container">

        <div class="row">

            <div class="col-xs-12">

                <h1 class="page-title caption1">Deneme</h1> 
                <div class="poll_vote">
                    <form method="post" action="#" name="anket-form" id="anket-form">

                        <input type="hidden" name="pollId" value="1" />

                        <ul class="poll_options">

                            <li><input type="radio" name="optionsId" id="option_1" value="1" /> <label for="option_1">test</label></li>
                            <li><input type="submit" value="Oy Ver" class="btn" name="btn_ok" onclick="javascript:return confirm('Onaylıyor mu sunuz?');" /></li>
                        </ul>

                    </form>

                </div>

                <div class="poll_result">



                    <div>Toplam 1 oy kullanıldı</div>


                    <ul class="poll_options2">

                        <li>
                            <div>test</div>

                            <div class="al carrier">
                                <div class="status al" rel="114">
                                    <span>% 100</span>
                                </div>
                            </div>

                            <div class="al isim">
                                <div class="count-vote al">0 oy</div>
                            </div>
                            <div class="clear"></div>
                        </li>

                    </ul>

                    <script type="text/javascript">
								$(document).ready(function(){
									$(".status").each(function() {
										var yuzde = $(this).attr("rel");
										$(this).filter(':not(:animated)').animate({width:yuzde+'%'},{duration:1000});
									});
								});
                    </script>



                </div>

            </div>

        </div>

    </div>

</div>

simya_web5/Views/Poll/Index.cshtml
@{
    ViewBag.Title = "Poll - egegen Internet Solutions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="section section-news"> 
    <div class="container">
        <h1 class="page-title caption1">Poll</h1> 
        <ul class="polls">
            <li><a href="@Url.Action("Details", "Poll")">Deneme</a></li>
        </ul>  
    </div>
</div>